In [ ]:
import pandas as pd
import numpy as np
import random

random.seed(42)
np.random.seed(42)

first_names = ["Ayesha","Bilal","Sana","Hamza","Zainab","Ali","Mahnoor","Usman","Fatima","Hassan",
               "Iqra","Ahmed","Sadia","Fahad","Mariam","Umar","Rabia","Zeeshan","Nida","Talha"]
last_names = ["Khan","Malik","Ahmed","Iqbal","Chaudhry","Butt","Raza","Hussain","Farooq","Sheikh"]

city_variants = {
    "Lahore": ["Lahore","lahore","LAHORE","Lahore ","Lahor"],
    "Karachi": ["Karachi","karachi","KARACHI","Karachi "],
    "Islamabad": ["Islamabad","islamabad","ISLAMABAD"],
    "Multan": ["Multan","multan"],
}
cities_clean = list(city_variants.keys())
universities = ["University of Education Lahore","LUMS","FAST-NUCES","Punjab University","COMSATS"]
degrees = ["BS English","BS Computer Science","BBA","BS Software Engineering","BS Mass Communication"]
skills_pool = ["Excel","Python","Canva","Content Writing","SEO","Social Media Marketing",
               "Graphic Design","Data Analysis","UI/UX Design","MS Office","Photoshop"]
roles = ["Digital Marketing Intern","Content Writing Intern","Graphic Design Intern",
         "Data Analytics Intern","UI/UX Design Intern","Virtual Assistant Intern"]
statuses = ["Applied","Shortlisted","Rejected","Selected"]

rows = []
for i in range(1, 121):
    fname, lname = random.choice(first_names), random.choice(last_names)
    age = int(np.random.normal(22, 2))
    city_clean = random.choice(cities_clean)
    city = random.choice(city_variants[city_clean])
    skills_str = ", ".join(random.sample(skills_pool, k=random.randint(2,4)))
    date = pd.Timestamp('2024-01-01') + pd.Timedelta(days=random.randint(0,150))
    date_str = date.strftime(random.choice(["%Y-%m-%d","%d/%m/%Y","%B %d, %Y"]))
    email = f"{fname.lower()}.{lname.lower()}{random.randint(1,99)}@gmail.com"
    rows.append([i, f"{fname} {lname}", age, city, random.choice(universities),
                 random.choice(degrees), skills_str, random.choice(roles),
                 date_str, random.choice(statuses), email])

df = pd.DataFrame(rows, columns=["applicant_id","full_name","age","city","university",
                                   "degree","skills","applied_role","application_date","status","email"])

for col in ["age","city","skills","email"]:
    df.loc[df.sample(frac=0.06).index, col] = np.nan

df.loc[df.sample(4).index, "age"] = [150, -5, 3, 99]
df = pd.concat([df, df.sample(6)], ignore_index=True)

df.head()

,applicant_id,full_name,age,city,university,degree,skills,applied_role,application_date,status,email
0,1,Hamza Khan,22.0,Islamabad,Punjab University,BS English,"Canva, Python",Digital Marketing Intern,2024-05-19,Applied,hamza.khan76@gmail.com
1,2,Mahnoor Iqbal,21.0,Lahor,COMSATS,BBA,"Photoshop, UI/UX Design",Digital Marketing Intern,2024-04-17,Shortlisted,mahnoor.iqbal58@gmail.com
2,3,Fahad Butt,23.0,NaN,FAST-NUCES,BBA,"Social Media Marketing, Python",UI/UX Design Intern,24/01/2024,Rejected,fahad.butt13@gmail.com
3,4,Bilal Hussain,25.0,Lahore,University of Education Lahore,BS English,"UI/UX Design, SEO",Virtual Assistant Intern,"April 02, 2024",Shortlisted,bilal.hussain25@gmail.com
4,5,Hassan Malik,21.0,Karachi,LUMS,BBA,"SEO, Data Analysis, Social Media Marketing",Virtual Assistant Intern,11/02/2024,Applied,hassan.malik46@gmail.com

In [ ]:
df.shape

(126, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   applicant_id      126 non-null    int64
 1   full_name         126 non-null    object
 2   age               120 non-null    float64
 3   city              118 non-null    object
 4   university        126 non-null    object
 5   degree            126 non-null    object
 6   skills            118 non-null    object
 7   applied_role      126 non-null    object
 8   application_date  126 non-null    object
 9   status            126 non-null    object
 10  email             119 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 11.0+ KB

In [ ]:
df.isnull().sum()

applicant_id        0
full_name           0
age                 6
city                8
university          0
degree              0
skills              8
applied_role        0
application_date    0
status              0
email               7
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(6)

In [ ]:
print(df.isnull().sum())

applicant_id        0
full_name           0
age                 6
city                8
university          0
degree              0
skills              8
applied_role        0
application_date    0
status              0
email               7
dtype: int64

In [ ]:
df['age'].describe()

count    120.000000
mean      22.691667
std       14.130125
min       -5.000000
25%       20.000000
50%       21.000000
75%       22.000000
max      150.000000
Name: age, dtype: float64

In [ ]:
df[(df['age'] < 19) | (df['age'] > 30)]

,applicant_id,full_name,age,city,university,degree,skills,applied_role,application_date,status,email
6,7,Sadia Chaudhry,3.0,lahore,LUMS,BS Computer Science,"Social Media Marketing, Content Writing, Data ...",Virtual Assistant Intern,2024-04-27,Rejected,sadia.chaudhry34@gmail.com
13,14,Nida Iqbal,18.0,Lahore,COMSATS,BS Computer Science,"Photoshop, Excel, Content Writing, Python",Graphic Design Intern,09/01/2024,Selected,nida.iqbal10@gmail.com
14,15,Mahnoor Farooq,18.0,Karachi,Punjab University,BBA,"Data Analysis, Graphic Design",Data Analytics Intern,2024-02-18,Selected,mahnoor.farooq13@gmail.com
37,38,Zeeshan Hussain,-5.0,Karachi,LUMS,BBA,NaN,Data Analytics Intern,13/05/2024,Applied,zeeshan.hussain81@gmail.com
49,50,Iqra Khan,18.0,multan,FAST-NUCES,BS Mass Communication,"Data Analysis, Content Writing",Virtual Assistant Intern,31/03/2024,Rejected,iqra.khan44@gmail.com
74,75,Ayesha Hussain,16.0,ISLAMABAD,Punjab University,BBA,"Canva, Python, Data Analysis, Social Media Mar...",Data Analytics Intern,30/05/2024,Rejected,ayesha.hussain82@gmail.com
79,80,Usman Raza,18.0,Islamabad,FAST-NUCES,BS Mass Communication,"Excel, SEO, UI/UX Design",Data Analytics Intern,01/02/2024,Rejected,usman.raza48@gmail.com
108,109,Mahnoor Butt,99.0,Multan,COMSATS,BS Mass Communication,"Canva, Photoshop",Virtual Assistant Intern,20/01/2024,Applied,mahnoor.butt13@gmail.com
110,111,Mariam Sheikh,18.0,ISLAMABAD,FAST-NUCES,BS Mass Communication,"Content Writing, UI/UX Design, Photoshop",Data Analytics Intern,20/03/2024,Selected,mariam.sheikh25@gmail.com
114,115,Zainab Ahmed,150.0,LAHORE,FAST-NUCES,BS Computer Science,"Canva, Data Analysis, MS Office",Content Writing Intern,2024-01-02,Selected,zainab.ahmed3@gmail.com

In [ ]:
df.loc[(df['age'] < 10) | (df['age'] > 80), 'age'] = np.nan

In [ ]:
df['age'].describe()

count    116.000000
mean      21.344828
std        1.779611
min       16.000000
25%       20.000000
50%       21.000000
75%       22.000000
max       26.000000
Name: age, dtype: float64

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())

In [ ]:
df['age'].describe()

count    126.000000
mean      21.317460
std        1.709507
min       16.000000
25%       20.000000
50%       21.000000
75%       22.000000
max       26.000000
Name: age, dtype: float64

In [ ]:
df.isnull().sum()

applicant_id        0
full_name           0
age                 0
city                8
university          0
degree              0
skills              8
applied_role        0
application_date    0
status              0
email               7
dtype: int64

In [ ]:
df.isnull().sum()

applicant_id        0
full_name           0
age                 0
city                8
university          0
degree              0
skills              8
applied_role        0
application_date    0
status              0
email               7
dtype: int64

In [ ]:
df['city'].unique()

array(['Islamabad', 'Lahor', nan, 'Lahore ', 'Karachi', 'karachi',
       'lahore', 'multan', 'Multan', 'islamabad', 'Lahore', 'Karachi ',
       'ISLAMABAD', 'LAHORE', 'KARACHI'], dtype=object)

In [ ]:
df['city'] = df['city'].str.strip().str.title()

In [ ]:
df['city'].unique()

array(['Islamabad', 'Lahor', nan, 'Lahore', 'Karachi', 'Multan'],
      dtype=object)

In [ ]:
df['city'] = df['city'].replace('Lahor', 'Lahore')

In [ ]:
df['city'].unique()

array(['Islamabad', 'Lahore', nan, 'Karachi', 'Multan'], dtype=object)

In [ ]:
df['skills'].unique()

array(['Canva, Python', 'Photoshop, UI/UX Design',
       'Social Media Marketing, Python', 'UI/UX Design, SEO',
       'SEO, Data Analysis, Social Media Marketing', nan,
       'Social Media Marketing, Content Writing, Data Analysis, Graphic Design',
       'Canva, UI/UX Design', 'MS Office, Data Analysis, UI/UX Design',
       'Excel, SEO, UI/UX Design',
       'Social Media Marketing, Data Analysis, Excel, Python',
       'Canva, Data Analysis',
       'Photoshop, Social Media Marketing, Data Analysis, UI/UX Design',
       'Photoshop, Excel, Content Writing, Python',
       'Data Analysis, Graphic Design',
       'Social Media Marketing, Python, Content Writing',
       'UI/UX Design, Python, Excel', 'Graphic Design, Excel',
       'MS Office, UI/UX Design',
       'Python, Canva, Photoshop, UI/UX Design',
       'Content Writing, Social Media Marketing, Photoshop',
       'Content Writing, UI/UX Design, SEO, Canva',
       'Photoshop, Python, Canva',
       'Photoshop, SEO, UI/UX Design, Data Analysis',
       'Data Analysis, UI/UX Design, Graphic Design, Excel', 'Excel, SEO',
       'Canva, Photoshop', 'Data Analysis, Content Writing',
       'SEO, Social Media Marketing', 'MS Office, Graphic Design',
       'SEO, UI/UX Design', 'Graphic Design, Canva, SEO, Photoshop',
       'Data Analysis, Canva, Python, SEO', 'Excel, Content Writing',
       'Photoshop, Excel', 'Data Analysis, UI/UX Design',
       'UI/UX Design, Python, Canva', 'Content Writing, Graphic Design',
       'UI/UX Design, Photoshop, Content Writing',
       'Graphic Design, Social Media Marketing, Content Writing',
       'Social Media Marketing, Content Writing',
       'Photoshop, Python, Content Writing', 'SEO, MS Office',
       'Social Media Marketing, UI/UX Design',
       'Social Media Marketing, Data Analysis, Canva', 'Python, SEO',
       'Graphic Design, Data Analysis',
       'Content Writing, SEO, Social Media Marketing, Data Analysis',
       'SEO, Content Writing', 'Photoshop, Data Analysis',
       'Python, Photoshop, Graphic Design',
       'MS Office, Photoshop, Content Writing',
       'Python, Content Writing, MS Office, SEO',
       'Excel, Content Writing, SEO',
       'UI/UX Design, Data Analysis, MS Office, Python',
       'Excel, Canva, Data Analysis, UI/UX Design',
       'Python, Canva, Social Media Marketing, Graphic Design',
       'Graphic Design, UI/UX Design', 'Content Writing, SEO',
       'Content Writing, Data Analysis, UI/UX Design',
       'SEO, Excel, Photoshop, UI/UX Design',
       'Content Writing, Photoshop, Graphic Design',
       'UI/UX Design, MS Office',
       'Photoshop, SEO, Content Writing, Python',
       'Social Media Marketing, Photoshop, Graphic Design',
       'MS Office, Content Writing, Data Analysis',
       'Canva, Python, Data Analysis, Social Media Marketing',
       'Graphic Design, MS Office',
       'Data Analysis, SEO, Content Writing, Social Media Marketing',
       'MS Office, Social Media Marketing',
       'SEO, Canva, Photoshop, Data Analysis',
       'UI/UX Design, Social Media Marketing, Content Writing, Python',
       'Content Writing, UI/UX Design',
       'Excel, Social Media Marketing, Content Writing',
       'Content Writing, Python, Data Analysis',
       'Content Writing, MS Office, Photoshop, UI/UX Design',
       'Excel, Canva, Photoshop, Social Media Marketing',
       'Data Analysis, Social Media Marketing, UI/UX Design',
       'Graphic Design, Python, Data Analysis',
       'Graphic Design, Python, Social Media Marketing',
       'Python, Social Media Marketing, Canva',
       'MS Office, SEO, Social Media Marketing',
       'Python, SEO, Content Writing',
       'SEO, Social Media Marketing, MS Office',
       'Data Analysis, Social Media Marketing, Canva',
       'Python, SEO, Data Analysis, Graphic Design',
       'Photoshop, MS Office, Data Analysis, SEO',
       'Social Media Marketing, Python, Excel',
       'Excel, Graphic Design, Photoshop',
       'Social Media Marketing, Canva',
       'SEO, Social Media Marketing, Content Writing', 'Canva, SEO',
       'Social Media Marketing, Canva, Data Analysis, Python',
       'Data Analysis, Excel, MS Office',
       'Photoshop, Content Writing, Social Media Marketing, Data Analysis',
       'Data Analysis, Photoshop, UI/UX Design, Canva',
       'Photoshop, Graphic Design, SEO, UI/UX Design',
       'Graphic Design, Social Media Marketing, Canva, Python',
       'Content Writing, UI/UX Design, Photoshop', 'MS Office, Canva',
       'SEO, Data Analysis',
       'Social Media Marketing, Content Writing, Graphic Design, Python',
       'Canva, Data Analysis, MS Office',
       'Content Writing, Canva, SEO, Graphic Design',
       'UI/UX Design, Photoshop, MS Office, Excel',
       'Photoshop, Python, Social Media Marketing, Canva',
       'Data Analysis, Excel, SEO, Content Writing'], dtype=object)

In [ ]:
df['skills'] = df['skills'].fillna('Not specified')

In [ ]:
df['skills'].isnull().sum()

np.int64(0)

In [ ]:
df = df.dropna(subset=['email'])

In [ ]:
df.shape

(119, 11)

In [ ]:
df[df.duplicated()]

,applicant_id,full_name,age,city,university,degree,skills,applied_role,application_date,status,email
120,11,Zainab Butt,21.0,NaN,University of Education Lahore,BS Computer Science,"Social Media Marketing, Data Analysis, Excel, ...",UI/UX Design Intern,02/04/2024,Applied,zainab.butt31@gmail.com
121,71,Zainab Raza,22.0,Karachi,COMSATS,BS Software Engineering,Not specified,Graphic Design Intern,21/01/2024,Selected,zainab.raza87@gmail.com
122,119,Ahmed Malik,24.0,Islamabad,FAST-NUCES,BS Computer Science,"Photoshop, Python, Social Media Marketing, Canva",Virtual Assistant Intern,12/01/2024,Selected,ahmed.malik70@gmail.com
123,110,Iqra Sheikh,21.0,Karachi,University of Education Lahore,BS Software Engineering,"Canva, Photoshop",Graphic Design Intern,"February 12, 2024",Shortlisted,iqra.sheikh57@gmail.com
124,114,Ayesha Raza,26.0,Lahore,FAST-NUCES,BS English,"Social Media Marketing, Content Writing, Graph...",Virtual Assistant Intern,2024-04-05,Rejected,ayesha.raza4@gmail.com
125,97,Ahmed Raza,22.0,Lahore,COMSATS,BS English,"Photoshop, MS Office, Data Analysis, SEO",Digital Marketing Intern,2024-01-12,Shortlisted,ahmed.raza51@gmail.com

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(113, 11)

In [ ]:
print(df.isnull().sum())
print(df.duplicated().sum())

applicant_id        0
full_name           0
age                 0
city                7
university          0
degree              0
skills              0
applied_role        0
application_date    0
status              0
email               0
dtype: int64
0

In [ ]:
df['city'] = df['city'].fillna('Not specified')

/tmp/ipykernel_4530/981479914.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = df['city'].fillna('Not specified')

In [ ]:
df['city'].unique()

array(['Islamabad', 'Lahore', 'Not specified', 'Karachi', 'Multan'],
      dtype=object)

In [ ]:
print(df.isnull().sum())
print(df.duplicated().sum())

applicant_id        0
full_name           0
age                 0
city                0
university          0
degree              0
skills              0
applied_role        0
application_date    0
status              0
email               0
dtype: int64
0

In [ ]:
df.to_csv('internship_applicants_cleaned.csv', index=False)